### ISSUE TITLE
Missing Spicetify settings; color.ini or CSS in user.css

### ISSUE THREAD

**Issue by falkecarlsen** [nboughton/dotfiles#1]
Stumbled upon your post in r/unixporn and noticed that your dots does not contain anything Spicetify-related as far as I could tell.

**Comment by nboughton** [comment]
Spicetify is pretty simple to enable and I'm just using the Nord theme from the spicetify-themes AUR package. You'll want to read [this](https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-aur) for some information on setting up Spicetify from the AUR.

**Comment by falkecarlsen** [comment]
> I'm just using the Nord theme from the spicetify-themes AUR package

That's what I was missing, thanks!
