### ISSUE TITLE
How to use waybar?

### ISSUE THREAD

**Issue by ayamir** [nboughton/dotfiles#2]
I encounter this when I want to start it.
![20201205_16h29m15s_grim](https://user-images.githubusercontent.com/61657399/101237892-4406bd80-3717-11eb-8bb8-9d94d6c0c2c3.png)

**Comment by nboughton** [comment]
You might need to disable the taskbar module in the waybar config as it only works with waybar-git

**Comment by nboughton** [comment]
If the weather script isn't working it might be worth tweaking it to fit your needs. The documentation for using wttr.in is here: https://github.com/chubin/wttr.in

**Comment by ayamir** [comment]
> If the weather script isn't working it might be worth tweaking it to fit your needs. The documentation for using wttr.in is here: https://github.com/chubin/wttr.in

Thanks, it works.
